### ISSUE TITLE
Do you have RKI Corona county data?

### ISSUE THREAD

**Issue by t-animal** [shouldibeworried/covid19#2]
I'm developing https://covid-karte.de and want to implement a timelapse-feature like you have, but not just with the total infections, but all the available data from that time. Do you have the historical RKI county data by any chance?

**Comment by shouldibeworried** [comment]
Hi @t-animal, I haven't actually added the timelapse feature to my website yet, so if you make it available via your website, that would be awesome! I'm using RKI data from here: https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.csv
It's broken down by individual reports from the health authorities to RKI, so it's super granular. I used pandas to aggregate it like so:
```python
    df = pd.read_csv(source_file, parse_dates=["Meldedatum"])
    pv = pd.pivot_table(df, values="AnzahlFall",
                        index=["Meldedatum"],
                        columns=["IdLandkreis"], aggfunc=np.sum, fill_value=0)
```

**Comment by t-animal** [comment]
Yes, I know and use this data, unfortunately you can't reliably reconstruct all old county data from it.
